import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import "./App.css";
import "h8k-components";
import FeedbackSystem from "./components/CodeReviewFeedback";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Code Review Feedback",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

const title = "Code Review Feedback";

const App = () => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="App">
          <h8k-navbar header={title}></h8k-navbar>
          <FeedbackSystem />
        </div>
      </body>
    </html>
  );
};

export default App;
