import "./App.css";
import "h8k-components";
import React from "react";
import FeedbackSystem from "./app/components/CodeReviewFeedback";

export const metadata = {
  title: "Code Review Feedback",
  description: "Generated by create next app",
};

const title = "Code Review Feedback";

const App = () => {
  return (
        <div className="App">
          <h8k-navbar header={title}></h8k-navbar>
          <FeedbackSystem />
        </div>
  );
};

export default App;
